permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: tendoasan
  email: tjuywb@gmail.com
  weibo: http://weibo.com/1896545711
  github: http://github.com/tendoasan
  linkedin: http://linkedin.com/in/wenbin-yu-36614b5a
# 站点信息
title: tendoasan的博客
description: tendoasan的博客自留地
url: 
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/tendoasan.jpg
favicon: /public/img/tendoasan.jpg

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: tendoasan

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Java
  - Sublime

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

gems: [jekyll-paginate]
