# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tendoasan's blogs
email: tjuywb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tendoasan的博客自留地。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tendoasan
github_username:  tendoasan

# Build settings
markdown: kramdown
